### PR TITLE
Adding a script to change the 'scaffold' app to a name of your choice and...

### PR DESCRIPTION
**Pull request by adamalton**
...update all references to it.

### CODE REVIEW

**Comment by martinallison** [comment]
Instead of doing this, we could make a [Django project template](https://docs.djangoproject.com/en/1.7/ref/django-admin/#startproject-projectname-destination) out of the djangae-scaffold app?

**Comment by adamalton** [comment]
Nice idea.  I look forward to your pull request :-)  Worth merging this in the meantime?

**Comment by pawciobiel** [comment]
@adamalton what version of `sed` do you use?

**Comment by astonecutter** [comment]
+1 @martinallison for the Django project template. Using a script seems to negate all the benefits that a simple `--template` can bring

**Comment by olasitarska** [comment]
I think it is still worth merging it. I'm gonna raise an issue for the template thing.

**Comment by olasitarska** [comment]
Thanks Adam!

**Pull request merged**
