### PR TITLE
Update Copyright Year

### PR DESCRIPTION
**Pull request by WillsB3**
Filing the important Pull Requests, I know...

### CODE REVIEW

**Comment by adamalton** [comment]
Shouldn't it be `2014-2017`?  Otherwise someone who's had a copy since 2015 can claim that they wrote it, because we'd be claiming that we wrote it in 2017.

**Comment by moggers87** [comment]
Their copy would still have the 2014 copyright notice. If they're deleted Potato's copyright notice then they don't have a license ☺. But yeah, you should be listing all years where there's been changes IMO.

The GNU project has these guidelines: https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

**Comment by WillsB3** [comment]
Updated

**Comment by adamalton** [comment]
@moggers87 raises a valid point!

Thanks @WillsB3, merging...

**Pull request merged**
